name: "foodpicasso-test-server"

services:
  php:
    build: ./docker/php
    container_name: foodpicasso-test-php
    restart: unless-stopped
    ports:
      - "5173:5173"
    env_file:
      - .env
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: foodpicasso
      DB_USER: root
    volumes:
      - .:/var/www
  nginx:
    image: nginx:1.27.0-alpine3.19
    container_name: foodpicasso-test-nginx
    restart: unless-stopped
    ports:
      - "${APP_PORT}:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
  mysql:
    image: mysql:9.0.1
    container_name: foodpicasso-test-mysql
    restart: unless-stopped
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: foodpicasso
